### ISSUE TITLE
Task Dependency Environmental Variable Ignored

### ISSUE THREAD

**Issue by elcfd** [elcfd/bitbake-docker#9]
https://github.com/elcfd/bitbake-docker/blob/796feab6ad836bf2b2e8b44e9323e332a41ac2fb/Taskfile.yml#L24

**Comment by elcfd** [comment]
```yml
version: '2'

silent: true

vars:
  IMAGES: all

tasks:
  default:
    summary: Build, test and release the docker images
    cmds:
      - task: build
      - task: test
      - task: release

  build:
    summary: Build the docker images
    cmds:
      - python3 image_creator.py build {{.IMAGES}}

  test:
    summary: Run the unit test suite
    deps:
      - task: build
    cmds:
      - python3 -m pytest -v --image_names {{.IMAGES}}

  release:
    summary: Push the built images to Dockerhub
    cmds:
      - python3 image_creator.py release {{.IMAGES}}
```
When running:
```
task test IMAGES=fedora-29
```
The build task is called but the value of IMAGES is not overridden and all images are built but only the fedora-29 image is tested.

When build is called on its own:
```
task build IMAGES=fedora-29
```
the variable overriding is successful and only the fedora-29 image is built
